// <auto-generated />
using System;
using EquipamentosMedicosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404160204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipamentosMedicosApi.Models.CourseClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("VafasDisponiveis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CourseClasses");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Inscricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoParticipante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeParticipante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusInscricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estoque = 15,
                            Nome = "Estetoscópio Profissional",
                            Preco = 289.90m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 2,
                            Estoque = 8,
                            Nome = "Monitor de Sinais Vitais",
                            Preco = 3599.00m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 3,
                            Estoque = 50,
                            Nome = "Luvas Cirúrgicas Estéreis - Caixa com 50 pares",
                            Preco = 159.90m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 4,
                            Estoque = 5,
                            Nome = "Desfibrilador Automático Externo (DEA)",
                            Preco = 8999.00m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 5,
                            Estoque = 20,
                            Nome = "Curso de Primeiros Socorros Básico",
                            Preco = 450.00m,
                            TipoProduto = "course"
                        },
                        new
                        {
                            Id = 6,
                            Estoque = 15,
                            Nome = "Curso de Suporte Avançado de Vida (ACLS)",
                            Preco = 1200.00m,
                            TipoProduto = "course"
                        },
                        new
                        {
                            Id = 7,
                            Estoque = 12,
                            Nome = "Workshop de Técnicas de Sutura",
                            Preco = 890.00m,
                            TipoProduto = "course"
                        },
                        new
                        {
                            Id = 8,
                            Estoque = 25,
                            Nome = "Curso de Biossegurança Hospitalar",
                            Preco = 350.00m,
                            TipoProduto = "course"
                        });
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.CourseClass", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.Product", "Produto")
                        .WithMany("Turmas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Inscricao", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.Order", "Pedido")
                        .WithMany("InscricoesGeradas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.CourseClass", "Turma")
                        .WithMany("Inscricoes")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Order", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.User", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.OrderItem", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.Order", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.Product", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.CourseClass", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.CourseClass", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Order", b =>
                {
                    b.Navigation("InscricoesGeradas");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Product", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.User", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
