// <auto-generated />
using EquipamentosMedicosApi.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522174500_SeedAdminUser")]
    partial class SeedAdminUser
    {
    }
}
