// <auto-generated />
using System;
using EquipamentosMedicosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipamentosMedicosApi.Models.CourseClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("VafasDisponiveis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CourseClasses");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Diagnóstico",
                            Date = "",
                            Description = "Estetoscópio de alta precisão com membrana dupla, ideal para ausculta cardíaca e pulmonar.",
                            Estoque = 15,
                            Image = "https://images.unsplash.com/photo-1655313719612-8248b2c4d1e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwZXF1aXBtZW50JTIwc3RldGhvc2NvcGV8ZW58MXx8fHwxNzczNTE3MTExfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "",
                            Location = "",
                            Nome = "Estetoscópio Profissional",
                            Preco = 289.90m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Monitoramento",
                            Date = "",
                            Description = "Monitor multiparamétrico com tela colorida para monitoramento de pressão arterial, frequência cardíaca e oximetria.",
                            Estoque = 8,
                            Image = "https://images.unsplash.com/photo-1770836037704-44bd8c7b6978?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3NwaXRhbCUyMGVxdWlwbWVudCUyMG1vbml0b3J8ZW58MXx8fHwxNzczNTE3MTEyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "",
                            Location = "",
                            Nome = "Monitor de Sinais Vitais",
                            Preco = 3599.00m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 3,
                            Category = "EPI",
                            Date = "",
                            Description = "Luvas cirúrgicas em látex, estéreis e de alta qualidade. Tamanhos variados disponíveis.",
                            Estoque = 50,
                            Image = "https://images.unsplash.com/photo-1758206523660-3ef5a51f1113?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwZ2xvdmVzJTIwc3VyZ2ljYWx8ZW58MXx8fHwxNzczNTE3MTEyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "",
                            Location = "",
                            Nome = "Luvas Cirúrgicas Estéreis - Caixa com 50 pares",
                            Preco = 159.90m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Emergência",
                            Date = "",
                            Description = "DEA portátil com instruções de voz e análise automática do ritmo cardíaco. Ideal para ambientes públicos.",
                            Estoque = 5,
                            Image = "https://images.unsplash.com/photo-1762161916712-09592fa05b20?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZWZpYnJpbGxhdG9yJTIwZW1lcmdlbmN5JTIwbWVkaWNhbHxlbnwxfHx8fDE3NzM1MTcxMTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "",
                            Location = "",
                            Nome = "Desfibrilador Automático Externo (DEA)",
                            Preco = 8999.00m,
                            TipoProduto = "equipment"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Primeiros Socorros",
                            Date = "15/04/2026 - 16/04/2026",
                            Description = "Aprenda técnicas essenciais de primeiros socorros, RCP e uso de DEA. Certificado reconhecido nacionalmente.",
                            Estoque = 20,
                            Image = "https://images.unsplash.com/photo-1622115585848-1d5b6e8af4e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXJzdCUyMGFpZCUyMHRyYWluaW5nfGVufDF8fHx8MTc3MzUxNzExM3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "Dr. Carlos Silva",
                            Location = "São Paulo - SP",
                            Nome = "Curso de Primeiros Socorros Básico",
                            Preco = 450.00m,
                            TipoProduto = "course"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Treinamento Avançado",
                            Date = "22/04/2026 - 23/04/2026",
                            Description = "Treinamento avançado para profissionais de saúde em emergências cardiovasculares. Carga horária de 16h.",
                            Estoque = 15,
                            Image = "https://images.unsplash.com/photo-1659353887019-b142198f2668?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwdHJhaW5pbmclMjBjb3Vyc2V8ZW58MXx8fHwxNzczNTE3MTEyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "Dra. Ana Paula Costa",
                            Location = "Rio de Janeiro - RJ",
                            Nome = "Curso de Suporte Avançado de Vida (ACLS)",
                            Preco = 1200.00m,
                            TipoProduto = "course"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Workshop",
                            Date = "10/05/2026",
                            Description = "Práticas intensivas de diferentes técnicas de sutura em modelos sintéticos. Aula prática com supervisão.",
                            Estoque = 12,
                            Image = "https://images.unsplash.com/photo-1659353887019-b142198f2668?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwdHJhaW5pbmclMjBjb3Vyc2V8ZW58MXx8fHwxNzczNTE3MTEyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "Dr. Roberto Mendes",
                            Location = "Belo Horizonte - MG",
                            Nome = "Workshop de Técnicas de Sutura",
                            Preco = 890.00m,
                            TipoProduto = "course"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Biossegurança",
                            Date = "18/04/2026",
                            Description = "Normas e práticas de biossegurança em ambientes hospitalares. Essencial para toda equipe de saúde.",
                            Estoque = 25,
                            Image = "https://images.unsplash.com/photo-1622115585848-1d5b6e8af4e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXJzdCUyMGFpZCUyMHRyYWluaW5nfGVufDF8fHx8MTc3MzUxNzExM3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
                            Instructor = "Enf. Marina Oliveira",
                            Location = "Curitiba - PR",
                            Nome = "Curso de Biossegurança Hospitalar",
                            Preco = 350.00m,
                            TipoProduto = "course"
                        });
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PromoCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MEDICO10",
                            Discount = 10m,
                            DiscountType = "percentage",
                            EndDate = "2026-12-31",
                            IsActive = true,
                            StartDate = "2026-04-01",
                            UsageCount = 5,
                            UsageLimit = 100
                        },
                        new
                        {
                            Id = 2,
                            Code = "PRIMEIRACOMPRA",
                            Discount = 50m,
                            DiscountType = "fixed",
                            EndDate = "2026-12-31",
                            IsActive = true,
                            StartDate = "2026-01-01",
                            UsageCount = 12
                        });
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnrollmentDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = "5",
                            CourseName = "Curso de Primeiros Socorros Básico",
                            Email = "joao.silva@email.com",
                            EnrollmentDate = "10/04/2026",
                            Name = "João Silva",
                            Phone = "(11) 98765-4321",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = "6",
                            CourseName = "Curso de Suporte Avançado de Vida (ACLS)",
                            Email = "maria.santos@email.com",
                            EnrollmentDate = "05/04/2026",
                            Name = "Maria Santos",
                            Phone = "(21) 99876-5432",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = "7",
                            CourseName = "Workshop de Técnicas de Sutura",
                            Email = "pedro.oliveira@email.com",
                            EnrollmentDate = "28/03/2026",
                            Name = "Pedro Oliveira",
                            Phone = "(31) 97654-3210",
                            Status = "completed"
                        });
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.CourseClass", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.Product", "Produto")
                        .WithMany("Turmas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Enrollment", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.CourseClass", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.Order", "Order")
                        .WithMany("Enrollments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Order");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Order", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.User", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.OrderItem", b =>
                {
                    b.HasOne("EquipamentosMedicosApi.Models.Order", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.Product", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipamentosMedicosApi.Models.CourseClass", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.CourseClass", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Order", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Product", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EquipamentosMedicosApi.Models.User", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
